### ISSUE TITLE
Question regarding running UN-CNVC

### ISSUE THREAD

**Issue by oalavijeh** [agilly/un-cnvc#1]
Dear Arthur, 

Many thanks for taking the time to create this tool. I have a large vcf file of all the CNV calls made by Canvas for 1000 or so patients (WGS data). It is all merged with all chromosome calls being within one file. How would I go about entering this into your algorithm? Would one still have to generate per chromosome depth files? 

Many thanks for your time and I look forward to your response. 

All the best

Omid

**Comment by agilly** [comment]
Dear Omid,

thanks for your interest, and sorry for the delay in replying to this ticket. Unfortunately I don't think UN-CNVc can be of use in your use case. As I understand, you have VCFs that contain CNVs already. UN-CNVc uses VCFs that contain SNPs to generate a CNV call file. 

Out of curiosity, what are you trying to do with your VCF file?

**Comment by oalavijeh** [comment]
Thanks for the reply. 

I have two merged vcf files of two cohorts; one with a rare disease (roughly 800 individuals) and a control group (17000 people) using 100K genome data. Each file is a "structural VCF" with all of the calls from Manta and Canvas in one file. I am trying to intersect these and pull only rare SVs from the disease cohort - as well as attempt to recalls these SVs with other methods (hence my interest in your project). 

All the best

Omid

**Comment by agilly** [comment]
For the intersect part, my intuition would be to convert the two files to bed and do something with `intersectBed`. If you would like to recall your two cohorts using `un-cnvc`, you will need VCFs containing only SNPs, called using e.g. GATK or `samtools mpileup`. Do you have such files?

**Comment by oalavijeh** [comment]
Thanks. Yes I am using bedtools as we speak! I have SNP VCFs also and will look to run un-cnvc at some point in the near future. Many thanks again for the help.
